feat(deps): bump the runtime-dependencies group across 1 directory with 2 updates (#348)
Bumps the runtime-dependencies group with 2 updates in the / directory:
[snowflake-connector-python](https://github.com/snowflakedb/snowflake-connector-python)
and [singer-sdk](https://github.com/meltano/sdk).

Updates `snowflake-connector-python` from 3.14.0 to 3.14.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/snowflakedb/snowflake-connector-python/releases">snowflake-connector-python's
releases</a>.</em></p>
<blockquote>
<h2>3.14.1</h2>
<ul>
<li>v3.14.1(April 21, 2025)
<ul>
<li>Added support for Python 3.13.
<ul>
<li>NOTE: Windows 64 support is still experimental and should not yet be
used for production environments.</li>
</ul>
</li>
<li>Dropped support for Python 3.8.</li>
<li>Added basic decimal floating-point type support.</li>
<li>Added experimental authentication methods.</li>
<li>Added support of GCS regional endpoints.</li>
<li>Added support of GCS virtual urls. See more: <a
href="https://cloud.google.com/storage/docs/request-endpoints#xml-api">https://cloud.google.com/storage/docs/request-endpoints#xml-api</a></li>
<li>Added <code>client_fetch_threads</code> experimental parameter to
better utilize threads for fetching query results.</li>
<li>Added <code>check_arrow_conversion_error_on_every_column</code>
connection property that can be set to <code>False</code> to restore
previous behaviour in which driver will ignore errors until it occurs in
the last column. This flag's purpose is to unblock workflows that may be
impacted by the bugfix and will be removed in later releases.</li>
<li>Lowered log levels from info to debug for some of the messages to
make the output easier to follow.</li>
<li>Allowed the connector to inherit a UUID4 generated upstream,
provided in statement parameters (field: <code>requestId</code>), rather
than automatically generate a UUID4 to use for the HTTP Request ID.</li>
<li>Improved logging in urllib3, boto3, botocore - assured data masking
even after migration to the external owned library in the future.</li>
<li>Improved error message for client-side query cancellations due to
timeouts.</li>
<li>Improved security and robustness for the temporary credentials cache
storage.</li>
<li>Fixed a bug that caused driver to fail silently on
<code>TO_DATE</code> arrow to python conversion when invalid date was
followed by the correct one.</li>
<li>Fixed expired S3 credentials update and increment retry when expired
credentials are found.</li>
<li>Deprecated <code>insecure_mode</code> connection property and
replaced it with <code>disable_ocsp_checks</code> with the same behavior
as the former property.</li>
</ul>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/4d76968b043c6c4fcd5378c6eca80372a4d28b31"><code>4d76968</code></a>
SNOW-1993520 update tested_reqs for 3.14.1 release (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2287">#2287</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/7a207f39e8b9d9408a92d543ec3adeadd7ace8ee"><code>7a207f3</code></a>
SNOW-1993520 Patch python connector version bump (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2286">#2286</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/6427d697221608ec43f37479de6e52af7ebe82d5"><code>6427d69</code></a>
NO-SNOW Update release date (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2284">#2284</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/f560c827880748ffbd0bb6c3a9a3f18f2fe5305a"><code>f560c82</code></a>
SNOW-2048239 revert zero timeout for oscp cache lock (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2283">#2283</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/b32dc8d4f77c729158e7736c279d3029dad26fb6"><code>b32dc8d</code></a>
Accept both v1 and v2 Entra ID issuer formats for WIF (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2281">#2281</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/3b64495640498dd703595cc6070347eb286c71dc"><code>3b64495</code></a>
NO-SNOW update 3.14.1 release notes (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2278">#2278</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/23f77a37c1d7b26370ba5913cc62da91ff17cf41"><code>23f77a3</code></a>
NO-SNOW acquiring a lock on local OCSP cache will use a timeout (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2280">#2280</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/27a4a9a7e02b038c1137d07b75593ff546274ad1"><code>27a4a9a</code></a>
NO-SNOW mark OCSP unit tests flaky (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2276">#2276</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/8c744de0d3f33852796e4d25cc6e9e860502a056"><code>8c744de</code></a>
SNOW-2032699: Use GCS virtual url based on the stage response (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2274">#2274</a>)</li>
<li><a
href="https://github.com/snowflakedb/snowflake-connector-python/commit/c384ce18b352343917fb06299d6eaaa21f30ca60"><code>c384ce1</code></a>
NO-SNOW Fetch wiremock in test_darwin.sh and test_windows.bat (<a
href="https://redirect.github.com/snowflakedb/snowflake-connector-python/issues/2273">#2273</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/snowflakedb/snowflake-connector-python/compare/v3.14.0...v3.14.1">compare
view</a></li>
</ul>
</details>
<br />

Updates `singer-sdk` from 0.45.4 to 0.45.10
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/releases">singer-sdk's
releases</a>.</em></p>
<blockquote>
<h2>v0.45.10 (2025-04-16)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>
Restore private <code>_http_headers</code> attribute of REST
streams</li>
</ul>
<h2>v0.45.9 (2025-04-15)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>
Update cookiecutter templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a> Do
not log a warning if <code>null</code> cannot be appended to schema
types</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>
Recognize <code>oneOf</code> fields in Singer schema helpers</li>
</ul>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
<h2>v0.45.6 (2025-04-11)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2961">#2961</a>
Conform <code>NaN</code>, <code>Infinity</code> and
<code>-Infinity</code> to null values</li>
</ul>
<h3>📚 Documentation Improvements</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2960">#2960</a>
Documented using <code>default=str</code> with <code>json.dumps</code>
in stream maps</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2955">#2955</a>
Documented the <code>ignore_parent_replication_key</code> stream
attribute</li>
</ul>
<h2>v0.45.5 (2025-04-04)</h2>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/meltano/sdk/blob/main/CHANGELOG.md">singer-sdk's
changelog</a>.</em></p>
<blockquote>
<h2>v0.45.10 (2025-04-16)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>
Restore private <code>_http_headers</code> attribute of REST
streams</li>
</ul>
<h2>v0.45.9 (2025-04-15)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>
Update cookiecutter templates</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a> Do
not log a warning if <code>null</code> cannot be appended to schema
types</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>
Recognize <code>oneOf</code> fields in Singer schema helpers</li>
</ul>
<h2>v0.45.8 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2965">#2965</a>
<code>AttributeError: object has no attribute '_requests_session'</code>
when accessing public property during stream initialization --
<em><strong>Thanks <a
href="https://github.com/ReubenFrankel"><code>@​ReubenFrankel</code></a>!</strong></em></li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2970">#2970</a>
Consider <code>oneOf</code> schemas when checking for <code>date</code>
and <code>datetime</code> types</li>
</ul>
<h2>v0.45.7 (2025-04-14)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2968">#2968</a>
<code>singer_sdk.singerlib.resolve_schema_references</code> now resolves
<code>oneOf</code> schema references</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2924">#2924</a>
Generate standard stream metadata for nested fields</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2940">#2940</a>
Ensure streams with hardcoded <code>schema</code> attributes (e.g. REST
and GraphQL streams) can have their schema overridden by the
catalog</li>
</ul>
<h3>📦 Packaging changes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2966">#2966</a> Add
a <code>fallback-version</code> for hatch vcs</li>
</ul>
<h2>v0.45.6 (2025-04-11)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2961">#2961</a>
Conform <code>NaN</code>, <code>Infinity</code> and
<code>-Infinity</code> to null values</li>
</ul>
<h3>📚 Documentation Improvements</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2960">#2960</a>
Documented using <code>default=str</code> with <code>json.dumps</code>
in stream maps</li>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2955">#2955</a>
Documented the <code>ignore_parent_replication_key</code> stream
attribute</li>
</ul>
<h2>v0.45.5 (2025-04-04)</h2>
<h3>🐛 Fixes</h3>
<ul>
<li><a
href="https://redirect.github.com/meltano/sdk/issues/2952">#2952</a>
Adapt field schema type to <code>string</code> when transformed with
stream maps using <code>json.dumps</code></li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/meltano/sdk/commit/aa54e2593eb1c4abf6303a6b75d7a7979f854a14"><code>aa54e25</code></a>
chore: Release v0.45.10 (<a
href="https://redirect.github.com/meltano/sdk/issues/2979">#2979</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/65575b5f72c9c3a69886a3805a07a61b7a72eb90"><code>65575b5</code></a>
fix: Restore private <code>_http_headers</code> attribute of REST
streams (<a
href="https://redirect.github.com/meltano/sdk/issues/2978">#2978</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/1f401b90acb7f75296c5b800936625ffd23c9a47"><code>1f401b9</code></a>
chore: Use <code>--no-color</code> flag for griffe</li>
<li><a
href="https://github.com/meltano/sdk/commit/80bd614106c02c84dc44d9ba9918de1d1251510b"><code>80bd614</code></a>
chore: Release v0.45.9 (<a
href="https://redirect.github.com/meltano/sdk/issues/2976">#2976</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/42c26dd3354fdb776315e6ecc650e2b870628847"><code>42c26dd</code></a>
fix: Update cookiecutter templates (<a
href="https://redirect.github.com/meltano/sdk/issues/2975">#2975</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/72939f2a371296681dff595ab9ba32a5dfa1b007"><code>72939f2</code></a>
fix: Do not log a warning if <code>null</code> cannot be appended to
schema types (<a
href="https://redirect.github.com/meltano/sdk/issues/2974">#2974</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/986a745edc8bda1347d147356649b02785900d83"><code>986a745</code></a>
fix: Recognize <code>oneOf</code> fields in Singer schema helpers (<a
href="https://redirect.github.com/meltano/sdk/issues/2973">#2973</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/b761e02d6a5272035c213037d2e59278b6662509"><code>b761e02</code></a>
chore: Release v0.45.8 (<a
href="https://redirect.github.com/meltano/sdk/issues/2972">#2972</a>)</li>
<li><a
href="https://github.com/meltano/sdk/commit/d7c7a816b6d490519c3d737241b384ebed8058b0"><code>d7c7a81</code></a>
chore: Expose <code>singer_sdk._singerlib.Catalog</code> for typing-only
code</li>
<li><a
href="https://github.com/meltano/sdk/commit/3c116d877d3ed9bfcaa70d7a639876efa13614a4"><code>3c116d8</code></a>
fix: <code>AttributeError: object has no attribute
'_requests_session'</code> when acces...</li>
<li>Additional commits viewable in <a
href="https://github.com/meltano/sdk/compare/v0.45.4...v0.45.10">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>